language: node_js
cache:
  directories:
    - ~/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      node_js: lts/*
      env: linting
      script: npm run lint
    - stage: test
      node_js: 9
      script: npm run test
    - node_js: 8
      script: npm run test
    - node_js: 6
      script: npm run test

after_success: npm run coveralls
